-- Company structure: the legal/operating entities and their physical branches.
--
-- Conventions used by every table in this schema:
--   * id            uuid primary key (generated by the application; the default covers manual SQL)
--   * created_at / updated_at   timestamptz, UTC
--   * created_by / updated_by   actor identifier (user id, or 'system' for jobs and migrations)
--   * version       optimistic-lock counter maintained by Hibernate
--   * deleted_at    soft delete: NULL = live row. Uniqueness is enforced on live rows only
--                   (partial unique indexes), so a deleted code or name can be reused.

CREATE TABLE organizations (
    id          uuid         NOT NULL DEFAULT gen_random_uuid(),
    code        varchar(50)  NOT NULL,
    name        varchar(200) NOT NULL,
    legal_name  varchar(200),
    tax_id      varchar(30),
    email       varchar(254),
    phone       varchar(30),
    status      varchar(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    created_by  varchar(100) NOT NULL,
    updated_at  timestamptz  NOT NULL DEFAULT now(),
    updated_by  varchar(100) NOT NULL,
    version     bigint       NOT NULL DEFAULT 0,
    deleted_at  timestamptz,
    CONSTRAINT pk_organizations PRIMARY KEY (id),
    CONSTRAINT ck_organizations_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX uq_organizations_code ON organizations (code) WHERE deleted_at IS NULL;

CREATE TABLE branches (
    id              uuid         NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid         NOT NULL,
    code            varchar(50)  NOT NULL,
    name            varchar(200) NOT NULL,
    address_line1   varchar(200),
    address_line2   varchar(200),
    city            varchar(100),
    state           varchar(100),
    postal_code     varchar(20),
    country_code    varchar(2)   NOT NULL DEFAULT 'IN',
    phone           varchar(30),
    email           varchar(254),
    head_office     boolean      NOT NULL DEFAULT false,
    active          boolean      NOT NULL DEFAULT true,
    created_at      timestamptz  NOT NULL DEFAULT now(),
    created_by      varchar(100) NOT NULL,
    updated_at      timestamptz  NOT NULL DEFAULT now(),
    updated_by      varchar(100) NOT NULL,
    version         bigint       NOT NULL DEFAULT 0,
    deleted_at      timestamptz,
    CONSTRAINT pk_branches PRIMARY KEY (id),
    CONSTRAINT fk_branches_organization FOREIGN KEY (organization_id) REFERENCES organizations (id),
    -- Target of users' composite foreign key, which guarantees a user's branch belongs to the user's organization.
    CONSTRAINT uq_branches_id_organization UNIQUE (id, organization_id)
);

-- Also serves lookups of an organization's branches (leading column organization_id).
CREATE UNIQUE INDEX uq_branches_organization_code ON branches (organization_id, code) WHERE deleted_at IS NULL;

-- At most one live head office per organization.
CREATE UNIQUE INDEX uq_branches_head_office ON branches (organization_id) WHERE head_office AND deleted_at IS NULL;
